var blocks = [],
    reset,
    rows_sld,
    columns_sld,
    playPause_btn,
    reset_btn,
    start_btn,
    random_sld,
    clear_btn,
    algorithms_rdos,
    algoName = undefined,
    rows = 40,
    columns = 40,
    size = 15,
    gap = 0,
    xr,
    yr,
    camZ,
    camP,
    openSet = [],
    openSetPrime = [],
    closedSet = [],
    path = [],
    start,
    end,
    playAlgo = false,
    zoom = 1,
    moveStart = false,
    moveEnd = false,
    progressPercent,
    progressBar,
    previousEstimate = 0,
    runRecursiveDivision = false,
    runDFSMaze = false;